### PR TITLE
Fix newer MEGA folder link parsing

### LINKED ISSUE #734: "Mega folder Link Error"
Image

Even there are no subfolders in the link I am getting this mega folder link detected error,

### LINKED ISSUE #741: mega folder link error
Hello mate!
Can you rephrase the links so i can download them ty

https://mega.nz/folder/ovAhGSwL#IQjH1oaiKv9IPCydHsk6kw

https://mega.nz/folder/tmZHGAKb#RfaNZoEw0LSYqaJdosvp4A

### PR DESCRIPTION
**Pull request by SeanCassiere**
This fixes folder parsing for newer MEGA folder links by handling the newer node key format without breaking the existing legacy link flow.

This patch was put together with AI help since I do not write Java for my day job, but I built the app locally and verified the fix with this MEGA URL: https://mega.nz/folder/ovAhGSwL#IQjH1oaiKv9IPCydHsk6kw (from https://github.com/tonikelope/megabasterd/issues/741#issue-4231168906)

Closes #734
Closes #741

### CODE REVIEW

File: src/main/java/com/tonikelope/megabasterd/FolderLinkDialog.java [hunk 1]
```diff
@@ -79,7 +79,7 @@ public FolderLinkDialog(MainPanelView parent, boolean modal, String link) {
         _total_space = 0L;
         _download = false;
         _download_links = new ArrayList<>();
-        _link = link;
+        _link = MiscTools.newMegaLinks2Legacy(link).trim();
```
Comment (SeanCassiere) [inline src/main/java/com/tonikelope/megabasterd/FolderLinkDialog.java:82]: now normalizes newer `mega.nz/folder/...` links into the legacy `#F!` format before parsing. This makes the dialog resilient even if a newer folder URL reaches it directly instead of coming through an earlier normalization step.

File: src/main/java/com/tonikelope/megabasterd/MegaAPI.java [hunk 2]
```diff
@@ -690,6 +701,59 @@ private HashMap _decAttr(String encAttr, byte[] key) {
         return res_map;
     }
 
+    private ArrayList<String> _extractNodeKeyCandidates(String raw_node_key) {
```
Comment (SeanCassiere) [inline src/main/java/com/tonikelope/megabasterd/MegaAPI.java:704]: splits a MEGA folder node `k` field into usable key candidates. It is needed because newer MEGA responses can include multiple `handle:key` entries in one field instead of the single-entry format the old code assumed.

File: src/main/java/com/tonikelope/megabasterd/MegaAPI.java [hunk 3]
```diff
@@ -690,6 +701,59 @@ private HashMap _decAttr(String encAttr, byte[] key) {
...
+                if (parts.length == 2 && !parts[0].isEmpty() && !parts[1].isEmpty()) {
+                    candidates.add(parts[1]);
+                }
+            }
+        }
+
+        return candidates;
+    }
+
+    private ResolvedNodeKey _resolveNodeKey(String raw_node_key, String folder_key, String attr) {
```
Comment (SeanCassiere) [inline src/main/java/com/tonikelope/megabasterd/MegaAPI.java]: tries the extracted key candidates until it finds one that can successfully decrypt the node attributes. It is needed because the parser can no longer assume there is only one valid node key, and it must pick the correct one without breaking older responses.

**Comment by SeanCassiere** [comment]
@tonikelope please feel free to tell me to buzz off regarding AI code going into your project!
Mostly just wanted a fix for this without having re-learn `public static void main` 😅

**Comment by xkti** [comment]
You don't need to bruteforce the correct handle. The first entry in any folder API response is the root folder, which is the sole handle needed for everything else.

See the code for my own downloader: https://github.com/xkti/mg-download/blob/ef1c395c9ff4cac549b2e45da5ca3b562a2bcccd/mg-download.sh#L510-L529

**Review by SeanCassiere — COMMENTED** [review]
@xkti based on your feedback, I've changed it to have it try the root handle first, which based on your comment should resolve (all the time?), but left in the fallback code-path for looping through the pairs ONLY of the root handle resolution fails.

What do you think? Like this approach better? and/or should I nuke that fallback code-path?

**Comment by xkti** [comment]
Looks OK and yes, the root handle *should* always be the correct one. Having your original idea as a fallback is a great idea.

I don't really know Java, but it looks about right to me.

**Comment by tonikelope** [comment]
Thank you very much! Now that I’ve wrapped up some other projects, I’ll see if I can really get stuck into my old friend MegaBasterd. And if we need to rely on AI, then we’ll rely on it – that’s what it’s there for. Adapt or die.
